export const THIS_USER_GOES_ONLINE = "THIS_USER_GOES_ONLINE";
export const THIS_USER_GOES_OFFLINE = "THIS_USER_GOES_OFFLINE";

export const THIS_USER_SENDS_MESSAGE = "THIS_USER_SENDS_MESSAGE";
export const A_USER_SENDS_MESSAGE = "A_USER_SENDS_MESSAGE";

export const THIS_USER_INVITES = "THIS_USER_INVITES";
export const A_USER_INVITES = "A_USER_INVITES";
