const THIS_USER_GOES_ONLINE = "THIS_USER_GOES_ONLINE";
const THIS_USER_GOES_OFFLINE = "THIS_USER_GOES_OFFLINE";

const THIS_USER_SENDS_MESSAGE = "THIS_USER_SENDS_MESSAGE";
const A_USER_SENDS_MESSAGE = "A_USER_SENDS_MESSAGE";

const THIS_USER_INVITES = "THIS_USER_INVITES";
const A_USER_INVITES = "A_USER_INVITES";

module.exports = {
    THIS_USER_GOES_ONLINE,
    THIS_USER_GOES_OFFLINE,
    THIS_USER_SENDS_MESSAGE,
    A_USER_SENDS_MESSAGE,
    THIS_USER_INVITES,
    A_USER_INVITES
}